/* Host build: every GTE macro of include/psyq/gtemac.h is a no-op (no GTE on the host; the rules never use it). */
#define gte_SetRotMatrix(r0) ((void)0)
#define gte_SetTransMatrix(r0) ((void)0)
#define gte_SetLightMatrix(r0) ((void)0)
#define gte_ldlv0(r0) ((void)0)
#define gte_ldclmv(r0) ((void)0)
#define gte_ldv0(r0) ((void)0)
#define gte_ldv0_u(r0) ((void)0)
#define gte_lddp(r0) ((void)0)
#define gte_ldsv(r0) ((void)0)
#define gte_gpf12() ((void)0)
#define gte_rtir() ((void)0)
#define gte_rt() ((void)0)
#define gte_ncs() ((void)0)
#define gte_ldsxy3(r0, r1, r2) ((void)0)
#define gte_ldsz3(r0, r1, r2) ((void)0)
#define gte_ldsz4(r0, r1, r2, r3) ((void)0)
#define gte_nclip() ((void)0)
#define gte_avsz3() ((void)0)
#define gte_avsz4() ((void)0)
#define gte_rtps() ((void)0)
#define gte_rtv0() ((void)0)
#define gte_stsxy(r0) ((void)0)
#define gte_stsv(r0) ((void)0)
#define gte_stclmv(r0) ((void)0)
#define gte_stopz(r0) ((void)0)
#define gte_stotz(r0) ((void)0)
#define gte_strgb(r0) ((void)0)
#define gte_stlvnl(r0) ((void)0)
#define gte_stszotz(r0) ((void)0)
#define gte_stflg(r0) ((void)0)
#define gte_MulMatrix0(r1, r2, r3) ((void)0)
#define gte_CompMatrix(r1, r2, r3) ((void)0)
