/* The SPU core's unit goldens (tests/spu/goldens.txt, generated by tests/spu/spu_ref.py from psx-spx) replayed through
 * the port's C core: psxstack/runtime/spu.c and spu_dsp.c, through spu.h's interface (register writes and reads, DMA, CD input,
 * renders) and spu_internal.h's pure pieces (ADPCM, interpolation, envelope, reverb addresses). spu_ref.py's docstring
 * has the file format. Built and run by tests/spu/run.sh.
 *
 *   spu_test [goldens.txt] [-v] [--dump CASE]   # exit 0: every op of every case matched
 *
 * --dump CASE prints the case's trace and render values, one per line, in spu_ref.py dump's format (to diff the two). */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "sha1.h"
#include "spu_internal.h"

static int verbose;
static const char *dump_case;
static int dumping;
static char case_name[128];
static long ops, failures, cases, failed_cases;
static int case_failed;
static long line_no;

static void fail(const char *fmt, const char *a, const char *b) {
    failures++;
    if (!case_failed) {
        failed_cases++;
        case_failed = 1;
    }
    if (failures <= 40) {
        printf("FAIL %s (line %ld): ", case_name, line_no);
        printf(fmt, a, b);
        printf("\n");
    }
}

static char *tok(void) {
    return strtok(NULL, " \t\r\n");
}

static long num(int base) {
    char *t = tok();
    if (t == NULL) {
        fprintf(stderr, "spu_test: line %ld: missing field\n", line_no);
        exit(2);
    }
    return strtol(t, NULL, base);
}

static size_t unhex(const char *hex, uint8_t *out, size_t cap) {
    size_t n = strlen(hex) / 2, i;
    if (n > cap) {
        fprintf(stderr, "spu_test: line %ld: hex field too long\n", line_no);
        exit(2);
    }
    for (i = 0; i < n; i++) {
        unsigned v;
        sscanf(hex + 2 * i, "%2x", &v);
        out[i] = (uint8_t)v;
    }
    return n;
}

static void sha1_hex(const void *data, size_t n, char hex[41]) {
    PortSha1 c;
    uint8_t d[20];
    port_sha1_init(&c);
    port_sha1_update(&c, data, n);
    port_sha1_final(&c, d);
    port_sha1_hex(d, hex);
}

static void put16(uint8_t *p, int32_t v) {
    p[0] = (uint8_t)v;
    p[1] = (uint8_t)((uint32_t)v >> 8);
}

static void put32(uint8_t *p, int32_t v) {
    put16(p, v);
    put16(p + 2, (int32_t)((uint32_t)v >> 16));
}

static void check_sha(const char *what, const char *got, const char *want) {
    char buf[64];
    if (strcmp(got, want) != 0) {
        snprintf(buf, sizeof(buf), "%s sha1", what);
        fail("%s: got %s", buf, got);
    }
}

static uint8_t big[1 << 20];

static void op_render(void) {
    long n = num(10), i;
    char *want = tok(), hex[41];
    int16_t *out = malloc((size_t)n * 4);

    spu_render(out, (int)n);
    for (i = 0; i < 2 * n; i++) {
        put16(big + 2 * i, out[i]);
    }
    sha1_hex(big, (size_t)n * 4, hex);
    if (dumping) {
        printf("# render %ld %s\n", n, want);
        for (i = 0; i < 2 * n; i++) {
            printf("%d\n", out[i]);
        }
    }
    check_sha("render", hex, want);
    free(out);
}

static void op_trace(void) {
    long n = num(10), i;
    uint32_t off = (uint32_t)num(16);
    char *want = tok(), hex[41];

    for (i = 0; i < n; i++) {
        uint16_t v;
        spu_render(NULL, 1);
        v = spu_read16(off);
        put16(big + 2 * i, v);
        if (dumping) {
            if (i == 0) {
                printf("# trace %ld %03x %s\n", n, off, want);
            }
            printf("%u\n", v);
        }
    }
    sha1_hex(big, (size_t)n * 2, hex);
    check_sha("trace", hex, want);
}

static void op_adpcm(void) {
    uint8_t block[16];
    int32_t hist[2];
    int16_t out[SPU_BLOCK_SAMPLES];
    int i, bad = 0;

    unhex(tok(), block, sizeof(block));
    hist[0] = (int32_t)num(10);
    hist[1] = (int32_t)num(10);
    spu_adpcm_decode(block, hist, out);
    for (i = 0; i < SPU_BLOCK_SAMPLES; i++) {
        bad |= out[i] != num(10);
    }
    bad |= hist[0] != num(10);
    bad |= hist[1] != num(10);
    if (bad) {
        fail("adpcm block %s%s", "", "");
    }
}

static void op_gauss(void) {
    unsigned i = (unsigned)num(10);
    int16_t s[4];
    int k;
    long want;
    int32_t got;
    char a[32], b[32];

    for (k = 0; k < 4; k++) {
        s[k] = (int16_t)num(10);
    }
    want = num(10);
    got = spu_gauss_interp(s, i);
    if (got != want) {
        snprintf(a, sizeof(a), "%d", got);
        snprintf(b, sizeof(b), "%ld", want);
        fail("gauss: got %s, want %s", a, b);
    }
}

static void op_env(void) {
    unsigned rate = (unsigned)num(16);
    int exp = (int)num(10), dec = (int)num(10), neg = (int)num(10);
    SpuEnvelope e;
    long n, i;
    char *want, hex[41];
    long level, counter;

    e.level = (int32_t)num(10);
    e.counter = 0;
    n = num(10);
    want = tok();
    level = num(10);
    counter = num(10);
    for (i = 0; i < n; i++) {
        spu_envelope_tick(&e, rate, exp, dec, neg);
        put32(big + 4 * i, e.level);
    }
    sha1_hex(big, (size_t)n * 4, hex);
    if (strcmp(hex, want) != 0 || e.level != level || (long)e.counter != counter) {
        char a[64];
        snprintf(a, sizeof(a), "rate %02x exp %d dec %d neg %d", rate, exp, dec, neg);
        fail("env %s%s", a, "");
    }
}

static void op_gausstable(void) {
    char *want = tok(), hex[41], a[32], b[32];
    long lo = num(16), hi = num(16);
    int32_t mn = 0x7FFFFFFF, mx = -0x7FFFFFFF;
    int i;

    for (i = 0; i < 512; i++) {
        put16(big + 2 * i, spu_gauss[i]);
    }
    sha1_hex(big, 1024, hex);
    check_sha("gauss table", hex, want);
    for (i = 0; i < 256; i++) {
        int32_t s = spu_gauss[i] + spu_gauss[0xFF - i] + spu_gauss[0x100 + i] + spu_gauss[0x1FF - i];
        mn = s < mn ? s : mn;
        mx = s > mx ? s : mx;
    }
    if (mn != lo || mx != hi || mn < 0x7F7F || mx > 0x7F81) {
        snprintf(a, sizeof(a), "%x..%x", mn, mx);
        snprintf(b, sizeof(b), "%lx..%lx", lo, hi);
        fail("gauss table sums %s, want %s", a, b);
    }
}

int main(int argc, char **argv) {
    const char *path = "tests/spu/goldens.txt";
    FILE *f;
    char *line = NULL;
    size_t cap = 0;
    int i;

    for (i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-v") == 0) {
            verbose = 1;
        } else if (strcmp(argv[i], "--dump") == 0 && i + 1 < argc) {
            dump_case = argv[++i];
        } else {
            path = argv[i];
        }
    }
    f = fopen(path, "r");
    if (f == NULL) {
        perror(path);
        return 2;
    }
    spu_init();
    while (getline(&line, &cap, f) > 0) {
        char *op;
        line_no++;
        op = strtok(line, " \t\r\n");
        if (op == NULL || op[0] == '#') {
            continue;
        }
        if (strcmp(op, "case") == 0) {
            snprintf(case_name, sizeof(case_name), "%s", tok());
            spu_reset();
            case_failed = 0;
            cases++;
            dumping = dump_case != NULL && strcmp(dump_case, case_name) == 0;
            continue;
        }
        if (strcmp(op, "end") == 0) {
            if (verbose) {
                printf("%s %s\n", case_failed ? "FAIL" : "ok  ", case_name);
            }
            continue;
        }
        ops++;
        if (strcmp(op, "w") == 0) {
            uint32_t off = (uint32_t)num(16);
            spu_write16(off, (uint16_t)num(16));
        } else if (strcmp(op, "r") == 0) {
            uint32_t off = (uint32_t)num(16);
            long want = num(16);
            uint16_t got = spu_read16(off);
            if (got != want) {
                char a[32], b[32];
                snprintf(a, sizeof(a), "%03x = %04x", off, got);
                snprintf(b, sizeof(b), "%04lx", want);
                fail("read %s, want %s", a, b);
            }
        } else if (strcmp(op, "dma") == 0) {
            size_t n;
            spu_write16(0x1A6, (uint16_t)num(16));
            n = unhex(tok(), big, sizeof(big));
            {
                uint16_t *h = malloc(n + 2);
                size_t k;
                for (k = 0; k < n / 2; k++) {
                    h[k] = (uint16_t)(big[2 * k] | big[2 * k + 1] << 8);
                }
                spu_dma_write(h, (uint32_t)(n / 2));
                free(h);
            }
        } else if (strcmp(op, "cd") == 0) {
            long frames = num(10), k;
            int16_t *s = malloc((size_t)frames * 4);
            unhex(tok(), big, sizeof(big));
            for (k = 0; k < 2 * frames; k++) {
                s[k] = (int16_t)(big[2 * k] | big[2 * k + 1] << 8);
            }
            spu_cd_input(s, (int)frames);
            free(s);
        } else if (strcmp(op, "render") == 0) {
            op_render();
        } else if (strcmp(op, "trace") == 0) {
            op_trace();
        } else if (strcmp(op, "ram") == 0) {
            uint32_t addr = (uint32_t)num(16), len = (uint32_t)num(16);
            char *want = tok(), hex[41];
            sha1_hex(spu_ram() + addr, len, hex);
            check_sha("ram", hex, want);
        } else if (strcmp(op, "revaddr") == 0) {
            int32_t off = (int32_t)num(10);
            uint32_t want = (uint32_t)num(16), got = spu_reverb_address(off);
            if (got != want) {
                char a[48], b[32];
                snprintf(a, sizeof(a), "%d -> %05x", off, got);
                snprintf(b, sizeof(b), "%05x", want);
                fail("reverb address %s, want %s", a, b);
            }
        } else if (strcmp(op, "adpcm") == 0) {
            op_adpcm();
        } else if (strcmp(op, "gauss") == 0) {
            op_gauss();
        } else if (strcmp(op, "env") == 0) {
            op_env();
        } else if (strcmp(op, "gausstable") == 0) {
            op_gausstable();
        } else {
            fprintf(stderr, "spu_test: line %ld: unknown op %s\n", line_no, op);
            return 2;
        }
    }
    free(line);
    fclose(f);
    if (dump_case != NULL) {
        return 0;
    }
    printf("spu_test: %ld cases, %ld ops: %s", cases, ops, failures ? "" : "all match\n");
    if (failures) {
        printf("%ld ops in %ld cases differ\n", failures, failed_cases);
    }
    return failures ? 1 : 0;
}
