/* The XA decoder's unit goldens (tests/xa/goldens.txt, generated by tests/xa/xa_ref.py from psx-spx) replayed through
 * the port's C: psxstack/psyq/xa.c, through xa.h. xa_ref.py's docstring has the file format. Built and run by
 * tests/xa/run.sh.
 *
 *   xa_test [goldens.txt] [-v]                 # exit 0: every op of every case matched
 *   xa_test --disc BIN LBA COUNT               # the XA audio sectors among COUNT raw sectors from LBA of the image:
 *                                              # "N sectors N37 SHA1 N44 SHA1" (xa_ref.py disc compares) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "sha1.h"
#include "xa.h"

static int verbose;
static char case_name[128];
static long ops, failures, cases, failed_cases;
static int case_failed;
static long line_no;
static XaDecoder dec;

static void fail(const char *what, const char *want, const char *got) {
    failures++;
    if (!case_failed) {
        failed_cases++;
        case_failed = 1;
    }
    if (failures <= 40) {
        printf("FAIL %s (line %ld) %s:\n  want %s\n  got  %s\n", case_name, line_no, what, want, got);
    }
}

static char *tok(void) {
    char *t = strtok(NULL, " \t\r\n");
    if (t == NULL) {
        fprintf(stderr, "xa_test: line %ld: missing field\n", line_no);
        exit(2);
    }
    return t;
}

static long num(void) {
    return strtol(tok(), NULL, 0);
}

static size_t unhex(const char *hex, uint8_t *out, size_t cap) {
    size_t n = strlen(hex) / 2, i;
    if (n > cap) {
        fprintf(stderr, "xa_test: line %ld: hex field too long\n", line_no);
        exit(2);
    }
    for (i = 0; i < n; i++) {
        unsigned v;
        sscanf(hex + 2 * i, "%2x", &v);
        out[i] = (uint8_t)v;
    }
    return n;
}

static void sha1_hex(const void *data, size_t n, char hex[41]) {
    PortSha1 c;
    uint8_t d[20];
    port_sha1_init(&c);
    port_sha1_update(&c, data, n);
    port_sha1_final(&c, d);
    port_sha1_hex(d, hex);
}

/* s16 values as little-endian bytes (the host may be either). */
static void s16le(const int16_t *v, size_t n, uint8_t *out) {
    size_t i;
    for (i = 0; i < n; i++) {
        out[2 * i] = (uint8_t)((uint16_t)v[i] & 0xFF);
        out[2 * i + 1] = (uint8_t)((uint16_t)v[i] >> 8);
    }
}

/* xa_ref.py xorshift_bytes / gen_sector. */
static void gen_sector(uint8_t ci, uint32_t seed, uint8_t *raw) {
    uint32_t x = seed;
    int i;

    memset(raw, 0, 2352);
    raw[15] = 2;
    for (i = 0; i < 2; i++) {
        raw[16 + 4 * i] = 1;
        raw[17 + 4 * i] = 1;
        raw[18 + 4 * i] = 0x64;
        raw[19 + 4 * i] = ci;
    }
    for (i = 0; i < 0x900; i++) {
        x ^= x << 13;
        x ^= x >> 17;
        x ^= x << 5;
        raw[24 + i] = (uint8_t)x;
    }
}

static void check_str(const char *what, const char *want, const char *got) {
    ops++;
    if (strcmp(want, got) != 0) {
        fail(what, want, got);
    } else if (verbose) {
        printf("ok %s %s\n", case_name, what);
    }
}

static void check_long(const char *what, long want, long got) {
    char a[32], b[32];
    snprintf(a, sizeof(a), "%ld", want);
    snprintf(b, sizeof(b), "%ld", got);
    check_str(what, a, b);
}

static void op_tables(void) {
    int16_t v[XA_PHASES * XA_TAPS > 8 ? XA_PHASES * XA_TAPS : 8];
    uint8_t b[sizeof(v)];
    char hex[41];
    int k, i;

    for (k = 0; k < XA_PHASES; k++) {
        for (i = 0; i < XA_TAPS; i++) {
            v[k * XA_TAPS + i] = xa_zigzag[k][i];
        }
    }
    s16le(v, XA_PHASES * XA_TAPS, b);
    sha1_hex(b, XA_PHASES * XA_TAPS * 2, hex);
    check_str("zigzag tables", tok(), hex);
    for (i = 0; i < 4; i++) {
        v[i] = xa_filter_pos[i];
        v[4 + i] = xa_filter_neg[i];
    }
    s16le(v, 8, b);
    sha1_hex(b, 16, hex);
    check_str("filters", tok(), hex);
}

static void op_group(void) {
    uint8_t ci = (uint8_t)strtol(tok(), NULL, 16), g[XA_GROUP_BYTES], b[2 * 2 * 224];
    int16_t left[224], right[224];
    char hex[41], got[160], want[160];
    long want_n;
    int n, stereo = XA_CI_STEREO(ci), i;

    memset(right, 0, sizeof(right));
    if (unhex(tok(), g, sizeof(g)) != XA_GROUP_BYTES) {
        fprintf(stderr, "xa_test: line %ld: a group is 128 bytes\n", line_no);
        exit(2);
    }
    want_n = num();
    n = xa_decode_group(&dec, ci, g, left, right);
    check_long("group samples", want_n, n);
    s16le(left, (size_t)n, b);
    if (stereo) {
        s16le(right, (size_t)n, b + 2 * n);
    }
    sha1_hex(b, (size_t)(stereo ? 4 * n : 2 * n), hex);
    check_str("group SHA-1", tok(), hex);
    want[0] = got[0] = 0;
    for (i = 0; i < 8; i++) {
        int v = i < 4 ? left[i] : stereo ? right[i - 4] : 0;
        snprintf(want + strlen(want), sizeof(want) - strlen(want), " %s", tok());
        snprintf(got + strlen(got), sizeof(got) - strlen(got), " %d", v);
    }
    check_str("group first samples", want, got);
}

static void op_hist(void) {
    dec.old[0] = (int32_t)num();
    dec.older[0] = (int32_t)num();
    dec.old[1] = (int32_t)num();
    dec.older[1] = (int32_t)num();
}

static void op_state(void) {
    char want[128], got[128];
    long v[6];
    int i;

    for (i = 0; i < 6; i++) {
        v[i] = num();
    }
    snprintf(want, sizeof(want), "%ld %ld %ld %ld %ld %ld", v[0], v[1], v[2], v[3], v[4], v[5]);
    snprintf(got, sizeof(got), "%ld %ld %ld %ld %lu %d", (long)dec.old[0], (long)dec.older[0], (long)dec.old[1],
             (long)dec.older[1], (unsigned long)dec.pos, dec.sixstep);
    check_str("state", want, got);
}

static void op_decode(void) {
    static uint8_t raw[2352], b[4 * XA_MAX_DECODED];
    static int16_t left[XA_MAX_DECODED], right[XA_MAX_DECODED];
    uint8_t ci = (uint8_t)strtol(tok(), NULL, 16);
    uint32_t seed = (uint32_t)num();
    XaDecoder copy = dec;
    char hex[41];
    long want_n = num();
    int n;

    gen_sector(ci, seed, raw);
    n = xa_decode_groups(&copy, ci, raw + 24, left, right);
    check_long("decode samples", want_n, n);
    s16le(left, (size_t)n, b);
    if (XA_CI_STEREO(ci)) {
        s16le(right, (size_t)n, b + 2 * n);
    }
    sha1_hex(b, (size_t)(XA_CI_STEREO(ci) ? 4 * n : 2 * n), hex);
    check_str("decode SHA-1", tok(), hex);
}

static void op_sector(void) {
    static uint8_t raw[2352], b[4 * XA_MAX_OUT];
    static int16_t out[2 * XA_MAX_OUT];
    uint8_t ci = (uint8_t)strtol(tok(), NULL, 16);
    uint32_t seed = (uint32_t)num();
    char hex[41];
    long want_n = num();
    int n;

    gen_sector(ci, seed, raw);
    n = xa_decode_sector(&dec, raw, out);
    check_long("sector frames", want_n, n);
    s16le(out, (size_t)n * 2, b);
    sha1_hex(b, (size_t)n * 4, hex);
    check_str("sector SHA-1", tok(), hex);
}

static void op_frames(void) {
    static uint8_t in[4 * 1024], b[4 * 2048];
    static int16_t out[2 * 2048];
    static char want[16384], got[16384];
    char hex[41], *t;
    size_t nin = unhex(tok(), in, sizeof(in)) / 4, i;
    long want_n = num();
    int n = 0;

    for (i = 0; i < nin; i++) {
        int16_t l = (int16_t)(in[4 * i] | in[4 * i + 1] << 8), r = (int16_t)(in[4 * i + 2] | in[4 * i + 3] << 8);
        n += xa_resample_frame(&dec, l, r, out + 2 * n);
    }
    check_long("frames out", want_n, n);
    s16le(out, (size_t)n * 2, b);
    sha1_hex(b, (size_t)n * 4, hex);
    check_str("frames SHA-1", tok(), hex);
    want[0] = got[0] = 0;
    while ((t = strtok(NULL, " \t\r\n")) != NULL) {
        snprintf(want + strlen(want), sizeof(want) - strlen(want), " %s", t);
    }
    if (want[0]) {
        for (i = 0; i < (size_t)n * 2; i++) {
            snprintf(got + strlen(got), sizeof(got) - strlen(got), " %d", out[i]);
        }
        check_str("frames samples", want, got);
    }
}

static int run_goldens(const char *path) {
    static char line[1 << 16];
    FILE *f = fopen(path, "r");

    if (f == NULL) {
        perror(path);
        return 2;
    }
    while (fgets(line, sizeof(line), f) != NULL) {
        char *op;

        line_no++;
        if (line[0] == '#' || (op = strtok(line, " \t\r\n")) == NULL) {
            continue;
        }
        if (strcmp(op, "case") == 0) {
            snprintf(case_name, sizeof(case_name), "%s", tok());
            case_failed = 0;
            cases++;
            xa_reset(&dec);
        } else if (strcmp(op, "end") == 0) {
            continue;
        } else if (strcmp(op, "tables") == 0) {
            op_tables();
        } else if (strcmp(op, "hist") == 0) {
            op_hist();
        } else if (strcmp(op, "group") == 0) {
            op_group();
        } else if (strcmp(op, "state") == 0) {
            op_state();
        } else if (strcmp(op, "decode") == 0) {
            op_decode();
        } else if (strcmp(op, "sector") == 0) {
            op_sector();
        } else if (strcmp(op, "frames") == 0) {
            op_frames();
        } else {
            fprintf(stderr, "xa_test: line %ld: unknown op %s\n", line_no, op);
            return 2;
        }
    }
    fclose(f);
    printf("xa goldens: %ld cases, %ld checks, %ld failed (%ld cases)\n", cases, ops, failures, failed_cases);
    return failures == 0 ? 0 : 1;
}

/* The audio sectors (MODE2, submode audio + real time) among `count` sectors from `lba`, decoded in order by one
 * decoder: the 37,800 Hz samples (L, R interleaved; mono on both) and the 44,100 Hz output, each as a SHA-1. */
static int run_disc(const char *bin, long lba, long count) {
    static uint8_t raw[2352], b[4 * XA_MAX_OUT];
    static int16_t left[XA_MAX_DECODED], right[XA_MAX_DECODED], out[2 * XA_MAX_OUT], pair[2 * XA_MAX_DECODED];
    PortSha1 h37, h44;
    uint8_t d[20];
    char x37[41], x44[41];
    long i, sectors = 0, n37 = 0, n44 = 0;
    FILE *f = fopen(bin, "rb");

    if (f == NULL) {
        perror(bin);
        return 2;
    }
    xa_reset(&dec);
    port_sha1_init(&h37);
    port_sha1_init(&h44);
    for (i = 0; i < count; i++) {
        XaDecoder copy;
        int n, k;

        if (fseek(f, (lba + i) * 2352L, SEEK_SET) != 0 || fread(raw, 1, sizeof(raw), f) != sizeof(raw)) {
            fprintf(stderr, "xa_test: %s: no sector %ld\n", bin, lba + i);
            fclose(f);
            return 2;
        }
        if (raw[15] != 2 || (raw[18] & 0x44) != 0x44) {
            continue;
        }
        sectors++;
        copy = dec;
        n = xa_decode_groups(&copy, raw[19], raw + 24, left, right);
        for (k = 0; k < n; k++) {
            pair[2 * k] = left[k];
            pair[2 * k + 1] = XA_CI_STEREO(raw[19]) ? right[k] : left[k];
        }
        s16le(pair, (size_t)n * 2, b);
        port_sha1_update(&h37, b, (size_t)n * 4);
        n37 += n;
        n = xa_decode_sector(&dec, raw, out);
        s16le(out, (size_t)n * 2, b);
        port_sha1_update(&h44, b, (size_t)n * 4);
        n44 += n;
    }
    fclose(f);
    port_sha1_final(&h37, d);
    port_sha1_hex(d, x37);
    port_sha1_final(&h44, d);
    port_sha1_hex(d, x44);
    printf("%ld sectors %ld %s %ld %s\n", sectors, n37, x37, n44, x44);
    return 0;
}

int main(int argc, char **argv) {
    const char *path = "tests/xa/goldens.txt";
    int i;

    if (argc == 5 && strcmp(argv[1], "--disc") == 0) {
        return run_disc(argv[2], strtol(argv[3], NULL, 0), strtol(argv[4], NULL, 0));
    }
    for (i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-v") == 0) {
            verbose = 1;
        } else {
            path = argv[i];
        }
    }
    return run_goldens(path);
}
